# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Example CI
on:
  merge_group:
    branches: [main]
jobs:
  SSH:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - run: npm test
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: 22
          script: |
            cd githunActionsTest
            sudo chmod -R ugo+rwX .
            git fetch --all
            git pull origin main
            npm i
            sudo pm2 restart 0
